### ISSUE TITLE
error in the preprocessing?

### ISSUE THREAD

**Issue by EmilMagni** [richardcsuwandi/hmm-word-segmentation#1]
Hi Richard
I tried to run this in jupyter notebook, but I think there may be something not working with the test_hs in the last part of the preprocessing as the test_label is not defined:

train_data, train_hs, train_wc = preprocess(train_data)
test_data, _, test_wc = preprocess(test_data)
_, test_hs, _ = preprocess(test_label)

**Comment by richardcsuwandi** [comment]
Hi Emil,

Thank you for pointing out this issue! It seems that I forgot to change the variable name for the test labels. You should try replacing test_label with test_gold, which is the defined in the data loading step. Once you have replaced that, I think the notebook should run without any problem.

Feel free to let me know if you have any other questions on the notebook.

**Comment by EmilMagni** [comment]
Thank you so much, that was the thing exactly. It should probably also be changed to _gold in the end where you show a random segmented sentence :)
